language: php

php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer require tecnick.com/tcpdf:6.*
    - composer install

script:
    - phpunit --bootstrap=vendor/autoload.php tests
